# Site settings
title: "takagotch"
email: me@fffabs.com
description: > # this means to ignore newlines until "baseurl:"
  fffabs &copy 2015 - go create!
baseurl: "https://takagotch.github.io/page26" # the subpath of your site, e.g. /blog/
url: "https://takagotch.github.io/page26" # the base hostname & protocol for your site
twitter_username: takagotch
github_username:  takagotch

# Build settings
markdown: kramdown
permalink: ":title/"
highlighter: pygments

# Pagination
paginate: 10
paginate_path: "blog/page/:num/"

# Minification
sass:
  style: compressed
